version: 'latest'
services:
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucon2021_prior
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
